### ISSUE TITLE
License ? Conditions of reuse

### ISSUE THREAD

**Issue by VolkerH** [taketwo/glasbey#10]
Hi, 
Thanks for the code to generate glasbey LUTs. 
Your code does not specify a license, which prevents its reuse in other projects, see e.g. here https://github.com/napari/napari/issues/454
Would you be willing to clarify terms of reusing your code by adding a License.txt file of your choice ? (BSD-3 would be permissive for use in other projects)

**Comment by taketwo** [comment]
The code is under MIT license since it's inception 6 years ago: https://github.com/taketwo/glasbey/blob/master/LICENSE.

**Comment by VolkerH** [comment]
Thank you. I was looking for the license file but I must have been
temporarily blind, sorry !

**Comment by taketwo** [comment]
NP!
