### ISSUE TITLE
Transformed code into object-oriented-format

### ISSUE THREAD

**Issue by TheBigFatTony** [taketwo/glasbey#3]
Hi, I re-factored your code so that it can be imported as a package from anywhere: https://github.com/TheBigFatTony/glasbey
Now, it is possible to do this:

```
>>> from Glasbey import Glasbey
>>> gb = Glasbey(base_palette="palettes/set1.txt", lightness_range=(10,100), hue_range=(10,100), chroma_range=(10,100), no_black=True)  # complicated example (demonstrate syntax)
>>> gb = Glasbey(base_palette="palettes/set1.txt")  # simplest example
Generating color table: 100% |###############################| Time:  0:00:34
>>> gb.get_palette(size=5)  # the palette already contains 5 colors, so return them instantaneously
array([[8.94117647e-01, 1.01960784e-01, 1.09803922e-01],
       [2.15686275e-01, 4.94117647e-01, 7.21568627e-01],
       [3.01960784e-01, 6.86274510e-01, 2.90196078e-01],
       [5.96078431e-01, 3.05882353e-01, 6.39215686e-01],
       [1.00000000e+00, 4.98039216e-01, 8.96505092e-17]])
>>> gb.get_palette(size=15)  # calculates colors 9-15
Generating palette: 100% |###################################| Time:  0:00:07
array([[ 8.94117647e-01,  1.01960784e-01,  1.09803922e-01],
       [ 2.15686275e-01,  4.94117647e-01,  7.21568627e-01],
       [ 3.01960784e-01,  6.86274510e-01,  2.90196078e-01],
       [ 5.96078431e-01,  3.05882353e-01,  6.39215686e-01],
       [ 1.00000000e+00,  4.98039216e-01,  8.96505092e-17],
       [ 1.00000000e+00,  1.00000000e+00,  2.00000000e-01],
       [ 6.50980392e-01,  3.37254902e-01,  1.56862745e-01],
       [ 9.68627451e-01,  5.05882353e-01,  7.49019608e-01],
       [ 6.00000000e-01,  6.00000000e-01,  6.00000000e-01],
       [ 7.17204074e-16,  2.62745098e-01,  3.92156863e-03],
       [ 1.43440815e-14,  1.00000000e+00,  1.00000000e+00],
       [-7.17204074e-16,  4.48252546e-16,  5.60784314e-01],
       [ 3.72549020e-01,  1.79301018e-16,  1.60784314e-01],
       [ 1.00000000e+00,  9.60784314e-01,  1.00000000e+00],
       [ 3.09803922e-01,  3.05882353e-01,  3.17647059e-01]])
>>> my_palette = gb.get_palette(size=15)  # returns them instantaneously because they're already calculated
>>> gb.view_palette(my_palette)  # opens imagemagick window
```

I added the possibility to automatically overwrite the base_palette with the newly calculated colors. (This is off by default.) This would be done like this:

```
>>> gb = Glasbey(base_palette="palettes/set1.txt", overwrite_base_palette=True)
>>> gb.get_palette(size=15)
Generating palette: 100% |#########################################################| Time:  0:00:07
array([[ 8.94117647e-01,  1.01960784e-01,  1.09803922e-01],
       [ 2.15686275e-01,  4.94117647e-01,  7.21568627e-01],
       [ 3.01960784e-01,  6.86274510e-01,  2.90196078e-01],
       [ 5.96078431e-01,  3.05882353e-01,  6.39215686e-01],
       [ 1.00000000e+00,  4.98039216e-01,  8.96505092e-17],
       [ 1.00000000e+00,  1.00000000e+00,  2.00000000e-01],
       [ 6.50980392e-01,  3.37254902e-01,  1.56862745e-01],
       [ 9.68627451e-01,  5.05882353e-01,  7.49019608e-01],
       [ 6.00000000e-01,  6.00000000e-01,  6.00000000e-01],
       [ 5.88229881e-42,  5.64082875e-42,  5.59612427e-42],
       [-8.96505092e-16,  2.90196078e-01, -1.54086813e-16],
       [ 1.43440815e-14,  1.00000000e+00,  1.00000000e+00],
       [ 1.17647059e-02,  8.96505092e-16,  5.88235294e-01],
       [ 3.56862745e-01,  1.79301018e-16,  1.52941176e-01],
       [ 1.00000000e+00,  9.60784314e-01,  1.00000000e+00]])
>>> len(open("palettes/set1.txt", 'r').readlines())
15
```

At the same time, the argument-parsing should work as it did before.

Also, I added unit tests to the project.

I hope you find this useful.

**Comment by taketwo** [comment]
Thanks. If you have time and interest, a pull request is welcome. However, I'd ask you to make several changes:

1. Base your commits on current master
2. Keep the main file/module name lowercase (as per standard [ref](https://www.python.org/dev/peps/pep-0008/#package-and-module-names))
3. Don't introduce unnecessary class (`PaletteViewer`) to hold a singe static method. A free function is just fine.

**Comment by TheBigFatTony** [comment]
Thanks for the feedback. (Actually, my changes were made on your current master, I just forked the wrong project!) I did what you suggested and hope it's okay now. If you have any more hints, don't hesitate to tell me.

I added another feature: Now, one can add rbg-arrays as a base-palette like so:
`gb = Glasbey(base_palette=[(255, 0, 0), (0, 255, 0), (0, 0, 255)])`

What are valid values for lightness_range, chroma_range and hue_range? I'd like to write this into the README.md and maybe add corresponding preconditions to the code.

PS: I noticed that commands with short 'size' parameters like `.glasbey.py --base-palette palettes/set1.txt 4 out.txt` fail with your code but not with mine.

**Comment by taketwo** [comment]
> What are valid values for lightness_range, chroma_range and hue_range? I'd like to write this into the README.md and maybe add corresponding preconditions to the code.

This is a contributed feature and, to be honest, I did not use it myself. I also could not find any information about valid ranges of _JCh_ space in `colorspacious` documentation.
